const rolesPermissions = {
  "Super Admin": {
    // Dashboard
    "Dashboard|Dashibodi": "v",
    // Mpangilio
    "Track Application|Fuatilia Ombi": "v",
    "Users|Watumiaji": "v,c,u,d",
    "Schools|Shule": "v,u",
    "Roles|Jukumu": "v,c,u,d",
    "Permissions|Ruhusa": "v,c,u,d",
    "Combinations|Michepuo": "v,c,u,d",
    "Biases|Tahasusi": "v,c,u,d",
    "Ranks|Ngazi": "v,c,u,d",
    "Hierarchies|Uongozi": "v,c,u,d",
    "Designations|Vyeo": "v,c,u,d",
    "Fees|Ada za Malipo": "v,c,u,d",
    "Attachments|Viambatisho": "v,c,u,d",
    "Wards|Kata": "v,c,u,d",
    "Streets|Mitaa": "v,c,u,d",
    "Districts|Wilaya": "v,c,u,d",
    "Regions|Mikoa": "v,c,u,d",
    "Zones|Kanda": "v,c,u,d",
    "Salaries|Mishahara": "v,c",
    "Applicants|Waombaji": "v,c,u,d",
    "Algorithm|Namba za Usajili": "v,c,u,d",
    "Workflow|Mpangilio wa utendaji kazi": "v,c,u,d",
    // Maombi
    "Initiate Schools|Ombi Kuanzisha Shule": "v,c,u",
    "School Owners and Managers|Ombi Wamiliki na Meneja wa Shule": "v,c,u",
    "School Registration Private|Ombi Kusajili Shule Binafsi": "v,c,u",
    "School Registration Government|Ombi Kusajili Shule Serikali": "v,c,u",
    "Change of Streams|Ombi Kuongeza Mikondo": "v,c,u",
    "Change School Name|Ombi Kubadili jina la shule ": "v,c,u",
    "Change of Bias|Ombi Kuongeza Tahasusi ": "v,c,u",
    "Addition of Domitory|Ombi Kuongeza Bweni ": "v,c,u",
    "Change of Hostel|Ombi Kuongeza Dahalia ": "v,c,u",
    "Change Registration Type|Ombi Kubadili Aina ya Usajili ": "v,c,u",
    "Change School Location|Ombi Kuhamisha Shule ": "v,c,u",
    "Change of School Owner|Ombi Kubadili Mmiliki wa Shule": "v,c,u",
    "Change of School Manager|Ombi Kubadili Meneja wa Shule ": "v,c,u",
    "Deregistration of Schools|Ombi Kufuta Usajili wa Shule ": "v,c,u",
    // Report
    "Established Schools Report|Ripoti ya Shule zilizoanzishwa": "v",
    "Registered School Report|Ripoti ya Usajili wa Shule": "v",
    "School Owners Report|Ripoti ya Uthibitisho wa Umiliki": "v",
    "School Managers Report|Ripoti ya Uthibitisho wa Umeneja": "v",
    "Change School Name Report|Ripoti ya Kubadili Jina la Shule": "v",
    "Change School Registration Type |Ripoti ya Kubadili Aina ya Usajili": "v",
    "Addition Of Domitory Report|Ripoti ya Kibali cha Kuongeza Bweni": "v",
    "Addition of Hostel Report|Ripoti Kibali cha Kuongeza Daharia": "v",
    "Change School Owners Report|Ripoti ya Kubadili Umiliki": "v",
    "Change School Managers Report|Ripoti ya Kubadili Umeneja": "v",
    "Change School Location Report|Ripoti ya Uhamisho wa Shule": "v",
    "Deregistration Report|Ripoti ya Kufuta Usajili": "v",
    "Addition of Streams Report|Ripoti ya Ombi Kuongeza Mikondo": "v",
    "Addition of Bias Report|Ripoti ya Kuongeza Tahasusi": "v",
    "Comments|Maoni": "v,c",
    // Audit Trail
    "Audit|Kaguzi": "v,c,u,d",
    "Profile|Profaili": "v,u",
    // Login Activity
    "Login Activity|Waliongia": "v",
    "Letters|Barua": "v",
    "Handover|Kaimisha": "c",
  },
  Admin: {
    "Users|Watumiaji": "v,c,u,d",
    "Initiate Schools|Ombi Kuanzisha Shule": "v,c,u",
    "School Owners and Managers|Ombi Wamiliki na Meneja wa Shule": "v,c,u",
    "School Registration Private|Ombi Kusajili Shule Binafsi": "v,c,u",
    "School Registration Government|Ombi Kusajili Shule Serikali": "v,c,u",
    "Change of Streams|Ombi Kuongeza Mikondo": "v,c,u",
    "Change School Name|Ombi Kubadili jina la shule ": "v,c,u",
    "Change of Bias|Ombi Kuongeza Tahasusi ": "v,c,u",
    "Addition of Domitory|Ombi Kuongeza Bweni ": "v,c,u",
    "Change of Hostel|Ombi Kuongeza Dahalia ": "v,c,u",
    "Change Registration Type|Ombi Kubadili Aina ya Usajili ": "v,c,u",
    "Change School Location|Ombi Kuhamisha Shule ": "v,c,u",
    "Change of School Owner|Ombi Kubadili Mmiliki wa Shule": "v,c,u",
    "Change of School Manager|Ombi Kubadili Meneja wa Shule ": "v,c,u",
    "Deregistration of Schools|Ombi Kufuta Usajili wa Shule ": "v,c,u",
    // Report
    "Established Schools Report|Ripoti ya Shule zilizoanzishwa": "v",
    "Registered School Report|Ripoti ya Usajili wa Shule": "v",
    "School Owners Report|Ripoti ya Uthibitisho wa Umiliki": "v",
    "School Managers Report|Ripoti ya Uthibitisho wa Umeneja": "v",
    "Change School Name Report|Ripoti ya Kubadili Jina la Shule": "v",
    "Change School Registration Type |Ripoti ya Kubadili Aina ya Usajili": "v",
    "Addition Of Domitory Report|Ripoti ya Kibali cha Kuongeza Bweni": "v",
    "Addition of Hostel Report|Ripoti Kibali cha Kuongeza Daharia": "v",
    "Change School Owners Report|Ripoti ya Kubadili Umiliki": "v",
    "Change School Managers Report|Ripoti ya Kubadili Umeneja": "v",
    "Change School Location Report|Ripoti ya Uhamisho wa Shule": "v",
    "Deregistration Report|Ripoti ya Kufuta Usajili": "v",
    "Addition of Streams Report|Ripoti ya Ombi Kuongeza Mikondo": "v",
    "Addition of Bias Report|Ripoti ya Kuongeza Tahasusi": "v",
    "Comments|Maoni": "v,c",
    "School Name|Jina la Shule": "u",
    "Attachments|Viambatisho": "v,c",
  },
  User: {
    // Maombi
    "Initiate Schools|Ombi Kuanzisha Shule": "v,c,u",
    "School Owners and Managers|Ombi Wamiliki na Meneja wa Shule": "v,c,u",
    "School Registration Private|Ombi Kusajili Shule Binafsi": "v,c,u",
    "School Registration Government|Ombi Kusajili Shule Serikali": "v,c,u",
    "Change of Streams|Ombi Kuongeza Mikondo": "v,c,u",
    "Change School Name|Ombi Kubadili jina la shule ": "v,c,u",
    "Change of Bias|Ombi Kuongeza Tahasusi ": "v,c,u",
    "Addition of Domitory|Ombi Kuongeza Bweni ": "v,c,u",
    "Change of Hostel|Ombi Kuongeza Dahalia ": "v,c,u",
    "Change Registration Type|Ombi Kubadili Aina ya Usajili ": "v,c,u",
    "Change School Location|Ombi Kuhamisha Shule ": "v,c,u",
    "Change of School Owner|Ombi Kubadili Mmiliki wa Shule": "v,c,u",
    "Change of School Manager|Ombi Kubadili Meneja wa Shule ": "v,c,u",
    "Deregistration of Schools|Ombi Kufuta Usajili wa Shule ": "v,c,u",
    // Report
    "Established Schools Report|Ripoti ya Shule zilizoanzishwa": "v",
    "Registered School Report|Ripoti ya Usajili wa Shule": "v",
    "School Owners Report|Ripoti ya Uthibitisho wa Umiliki": "v",
    "School Managers Report|Ripoti ya Uthibitisho wa Umeneja": "v",
    "Change School Name Report|Ripoti ya Kubadili Jina la Shule": "v",
    "Change School Registration Type |Ripoti ya Kubadili Aina ya Usajili": "v",
    "Addition Of Domitory Report|Ripoti ya Kibali cha Kuongeza Bweni": "v",
    "Addition of Hostel Report|Ripoti Kibali cha Kuongeza Daharia": "v",
    "Change School Owners Report|Ripoti ya Kubadili Umiliki": "v",
    "Change School Managers Report|Ripoti ya Kubadili Umeneja": "v",
    "Change School Location Report|Ripoti ya Uhamisho wa Shule": "v",
    "Deregistration Report|Ripoti ya Kufuta Usajili": "v",
    "Addition of Streams Report|Ripoti ya Ombi Kuongeza Mikondo": "v",
    "Addition of Bias Report|Ripoti ya Kuongeza Tahasusi": "v",
    "Comments|Maoni": "v,c",
    "School Name|Jina la Shule": "u",
    "Attachments|Viambatisho": "v,c",
  },
  Auditor: {
    "Audit|Kaguzi": "v",
  },
};
const defaultPermissions = {
  Dashboard: "v",
  Profile : "v,u",
  Letters : "v",
};
const translations = {
  en: {
    v: "view",
    c: "create",
    u: "update",
    d: "delete",
    r: "restore",
  },
  sw: {
    v: "ona",
    c: "tengeneza",
    u: "badili",
    d: "futa",
    r: "rudisha",
  },
};

module.exports = {rolesPermissions , translations , defaultPermissions}
