const rolesPermissions = {
  "Super Admin": {
    // Dashboard
    "Dashboard|Dashibodi": "v",
    // Mpangilio
    "Track Application|Fuatilia Ombi": "v",
    "Users|Watumiaji": "v,c,u,d",
    "Schools|Shule": "v,u",
    "Roles|Jukumu": "v,c,u,d",
    "Permissions|Ruhusa": "v,c,u,d",
    "Combinations|Michepuo": "v,c,u,d",
    "Biases|Tahasusi": "v,c,u,d",
    "Ranks|Ngazi": "v,c,u,d",
    "Hierarchies|Uongozi": "v,c,u,d",
    "Designations|Vyeo": "v,c,u,d",
    "Fees|Ada za Malipo": "v,c,u,d",
    "Attachments|Viambatisho": "v,up,u,d",
    "Wards|Kata": "v,c,u,d",
    "Streets|Mitaa": "v,c,u,d",
    "Districts|Wilaya": "v,c,u,d",
    "Regions|Mikoa": "v,c,u,d",
    "Zones|Kanda": "v,c,u,d",
    "Applicants|Waombaji": "v,c,u,d",
    "Algorithm|Namba za Usajili": "v,c,u,d",
    "Workflow|Mpangilio wa utendaji kazi": "v,c,u,d",
    // Report
    "Established Schools Report|Ripoti ya Shule zilizoanzishwa": "v",
    "Registered School Report|Ripoti ya Usajili wa Shule": "v",
    "School Owners Report|Ripoti ya Uthibitisho wa Umiliki": "v",
    "School Managers Report|Ripoti ya Uthibitisho wa Umeneja": "v",
    "Change School Name Report|Ripoti ya Kubadili Jina la Shule": "v",
    "Change School Registration Type |Ripoti ya Kubadili Aina ya Usajili": "v",
    "Addition Of Domitory Report|Ripoti ya Kibali cha Kuongeza Bweni": "v",
    "Addition of Hostel Report|Ripoti Kibali cha Kuongeza Daharia": "v",
    "Change School Owners Report|Ripoti ya Kubadili Umiliki": "v",
    "Change School Managers Report|Ripoti ya Kubadili Umeneja": "v",
    "Change School Location Report|Ripoti ya Uhamisho wa Shule": "v",
    "Deregistration Report|Ripoti ya Kufuta Usajili": "v",
    "Addition of Streams Report|Ripoti ya Ombi Kuongeza Mikondo": "v",
    "Addition of Bias Report|Ripoti ya Kuongeza Tahasusi": "v",
    "Comments|Maoni": "v,c",
    // Audit Trail
    "Audit|Kaguzi": "v,c,u,d",
    "Profile|Profaili": "v,u",
    // Login Activity
    "Login Activity|Waliongia": "v",
    "Letters|Barua": "v",
    "Handover|Kaimisha": "c",
  },
  Admin: {
    "Users|Watumiaji": "v,c,u,d",
    // Report
    "Established Schools Report|Ripoti ya Shule zilizoanzishwa": "v",
    "Registered School Report|Ripoti ya Usajili wa Shule": "v",
    "School Owners Report|Ripoti ya Uthibitisho wa Umiliki": "v",
    "School Managers Report|Ripoti ya Uthibitisho wa Umeneja": "v",
    "Change School Name Report|Ripoti ya Kubadili Jina la Shule": "v",
    "Change School Registration Type |Ripoti ya Kubadili Aina ya Usajili": "v",
    "Addition Of Domitory Report|Ripoti ya Kibali cha Kuongeza Bweni": "v",
    "Addition of Hostel Report|Ripoti Kibali cha Kuongeza Daharia": "v",
    "Change School Owners Report|Ripoti ya Kubadili Umiliki": "v",
    "Change School Managers Report|Ripoti ya Kubadili Umeneja": "v",
    "Change School Location Report|Ripoti ya Uhamisho wa Shule": "v",
    "Deregistration Report|Ripoti ya Kufuta Usajili": "v",
    "Addition of Streams Report|Ripoti ya Ombi Kuongeza Mikondo": "v",
    "Addition of Bias Report|Ripoti ya Kuongeza Tahasusi": "v",
    "Comments|Maoni": "v,c",
    "School Name|Jina la Shule": "u",
    "Attachments|Viambatisho": "v,c",
  },
  User: {
    // Report
    "Established Schools Report|Ripoti ya Shule zilizoanzishwa": "v",
    "Registered School Report|Ripoti ya Usajili wa Shule": "v",
    "School Owners Report|Ripoti ya Uthibitisho wa Umiliki": "v",
    "School Managers Report|Ripoti ya Uthibitisho wa Umeneja": "v",
    "Change School Name Report|Ripoti ya Kubadili Jina la Shule": "v",
    "Change School Registration Type |Ripoti ya Kubadili Aina ya Usajili": "v",
    "Addition Of Domitory Report|Ripoti ya Kibali cha Kuongeza Bweni": "v",
    "Addition of Hostel Report|Ripoti Kibali cha Kuongeza Daharia": "v",
    "Change School Owners Report|Ripoti ya Kubadili Umiliki": "v",
    "Change School Managers Report|Ripoti ya Kubadili Umeneja": "v",
    "Change School Location Report|Ripoti ya Uhamisho wa Shule": "v",
    "Deregistration Report|Ripoti ya Kufuta Usajili": "v",
    "Addition of Streams Report|Ripoti ya Ombi Kuongeza Mikondo": "v",
    "Addition of Bias Report|Ripoti ya Kuongeza Tahasusi": "v",
    "Comments|Maoni": "v,c",
    "School Name|Jina la Shule": "u",
    "Attachments|Viambatisho": "v,c",
  },
  Auditor: {
    "Audit|Kaguzi": "v",
  },
};
const defaultPermissions = {
  Dashboard: "v",
  Profile : "v,u",
  Letters : "v",
};
const translations = {
  en: {
    v: "view",
    c: "create",
    u: "update",
    d: "delete",
    r: "restore",
    up: 'upload',
  },
  sw: {
    v: "ona",
    c: "tengeneza",
    u: "badili",
    d: "futa",
    r: "rudisha",
    up: 'pandisha'
  },
};

module.exports = {rolesPermissions , translations , defaultPermissions}
